<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{

public function queryOwnedBy($user) {

    $query = $this->createQueryBuilder('a')
            ->from('AppBundle:Company', 'u')
            ->where('u.CreatorId = :id')                
            ->setParameter('id', $user->getId());

    return $query;
}

public function findOwnedBy($user) {
    return $this->queryOwnedBy($user)
            ->getQuery()
            ->getResult();
}


}
